
insert into T_ACCOUNT (IDNUMBER, NAME) values ('1234', 'Keri Lee');
insert into T_ACCOUNT (IDNUMBER, NAME) values ('1235', 'Dollie R. Schnidt');
insert into T_ACCOUNT (IDNUMBER, NAME) values ('1236', 'Cornelia J. LeClerc');
insert into T_ACCOUNT (IDNUMBER, NAME) values ('1237', 'Cynthia Rau');
insert into T_ACCOUNT (IDNUMBER, NAME) values ('1238', 'Douglas R. Cobbs');
insert into T_ACCOUNT (IDNUMBER, NAME) values ('1239', 'Michael Patel');
insert into T_ACCOUNT (IDNUMBER, NAME) values ('1240', 'Suzanne Wong');
insert into T_ACCOUNT (IDNUMBER, NAME) values ('1241', 'Ivan C. Jaya');
insert into T_ACCOUNT (IDNUMBER, NAME) values ('1242', 'Ida Ketterer');
insert into T_ACCOUNT (IDNUMBER, NAME) values ('1243', 'Laina Ochoa Lucero');
insert into T_ACCOUNT (IDNUMBER, NAME) values ('1244', 'Wesley M. Montana');
insert into T_ACCOUNT (IDNUMBER, NAME) values ('1245', 'Leslie F. McCleary');
insert into T_ACCOUNT (IDNUMBER, NAME) values ('1246', 'Sayeed D. Mudra');
insert into T_ACCOUNT (IDNUMBER, NAME) values ('1247', 'Pietronella J. Domingo');
insert into T_ACCOUNT (IDNUMBER, NAME) values ('1248', 'John S. O''Leary');
insert into T_ACCOUNT (IDNUMBER, NAME) values ('1249', 'Gladys D. Smith');
insert into T_ACCOUNT (IDNUMBER, NAME) values ('1250', 'Sally O. Thygesen');
insert into T_ACCOUNT (IDNUMBER, NAME) values ('1251', 'Rachel Vogt');
insert into T_ACCOUNT (IDNUMBER, NAME) values ('1252', 'Julia DeLong');
insert into T_ACCOUNT (IDNUMBER, NAME) values ('1253', 'Mark T. Rizzoli');
insert into T_ACCOUNT (IDNUMBER, NAME) values ('1254', 'Maria J. Angelo');
